name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: southamerica-east1
  SERVICE_NAME: gcr-ml
  BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Authentication
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.RUN_SA_KEY }}'

    # Setup gcloud CLI
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --config cloudbuild.yaml \
          --substitutions _BASIC_AUTH_USERNAME=$BASIC_AUTH_USERNAME,_BASIC_AUTH_PASSWORD=$BASIC_AUTH_PASSWORD,_IMAGE_TAG=southamerica-east1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "southamerica-east1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated \
          --port 8080